apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nginx-pod-pvc
spec:
   resources:
      requests:
         storage: 2Gi
   accessModes:
   - ReadWriteOnce
   storageClassName: nginx-storageclass
