apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: nginx-storageclass
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
parameters:
   type: pd-standard
   replication-type: none
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-central1-a

   
