apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
spec:
   containers:
   - name: nginx-ctn
     image: nginx
     volumeMounts:
     - name: nginx-pod-vol
       mountPath: /app/
   volumes:
   - name: nginx-pod-vol
     configMap:
        name: nginx-map
