apiVersion: v1
kind: Pod
metadata:
   name: gcepd-pod
spec:
   containers:
   - name: sample-ctn
     image: centos
     volumeMounts:
     - name: gcepd-vol
       mountPath: /app/
     command: ["tail","-f","/dev/null"]
   volumes:
   - name: gcepd-vol
     gcePersistentDisk:
        pdName: mydisk
