apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
spec:
   containers:
   - name: nginx-ctn
     image: nginx
     volumeMounts:
     - name: nginx-vol
       mountPath: /data/
   volumes:
   - name: nginx-vol
     persistentVolumeClaim:
        claimName: nginx-pod-pvc
