apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
spec:
   containers:
   - name: nginx-ctn
     image: nginx
     volumeMounts:
     - name: nginx-secret
       mountPath: /app/
   volumes:
   - name: nginx-secret
     secret:
        secretName: nginx-secret
